# Generated by Django 2.0 on 2017-12-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0002_task_workflow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sqwbase.Workflow'),
        ),
    ]
