# Generated by Django 2.0 on 2018-01-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0002_calculation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='analysis',
            field=models.TextField(blank=True),
        ),
    ]
