# Generated by Django 2.0 on 2018-01-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0003_workflow_analysis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='analysis',
        ),
        migrations.AddField(
            model_name='calculation',
            name='analysis',
            field=models.TextField(blank=True),
        ),
    ]
