# Generated by Django 2.0 on 2017-12-21 12:21

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0003_auto_20171221_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sqwbase.Task'),
        ),
    ]
