# Generated by Django 2.0 on 2018-01-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0004_auto_20180102_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='analysis',
        ),
        migrations.AddField(
            model_name='task',
            name='analysis',
            field=models.TextField(blank=True),
        ),
    ]
