# Generated by Django 2.0 on 2017-12-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0004_auto_20171221_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sqwbase.Project')),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='workflow_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='calculation_path',
        ),
        migrations.AddField(
            model_name='calculation',
            name='local_path',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='calculation',
            name='remote_path',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='calculation',
            name='molecule',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sqwbase.Molecule'),
            preserve_default=False,
        ),
    ]
