# Generated by Django 2.0 on 2018-01-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0005_auto_20180102_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
