# Generated by Django 2.0 on 2018-01-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0006_solventmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='solvent',
            field=models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='sqwbase.SolventModel'),
            preserve_default=False,
        ),
    ]
