# Generated by Django 2.0 on 2018-01-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0007_calculation_solvent'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
