# Generated by Django 2.0 on 2017-12-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0007_auto_20171222_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='basis',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sqwbase.Basis'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculation',
            name='method',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sqwbase.Method'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calculation',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='sqwbase.Program'),
            preserve_default=False,
        ),
    ]
