# Generated by Django 2.0 on 2017-12-22 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0008_auto_20171222_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='basis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sqwbase.Basis'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sqwbase.Method'),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sqwbase.Program'),
        ),
    ]
