# Generated by Django 2.0 on 2018-01-16 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0008_molecule_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='molecule',
            old_name='comment',
            new_name='description',
        ),
    ]
