# Generated by Django 2.0 on 2018-01-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0009_auto_20180116_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='pdb_file',
            field=models.FileField(blank=True, upload_to='pdbs/'),
        ),
    ]
