# Generated by Django 2.0 on 2017-12-22 14:15

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0009_auto_20171222_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='task',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sqwbase.Task'),
        ),
    ]
