# Generated by Django 2.0 on 2018-01-17 06:19

from django.db import migrations, models
import sqwbase.models


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0010_calculation_pdb_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='pdb_file',
            field=models.FileField(blank=True, upload_to=sqwbase.models.rename_pdb),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='pdb_file',
            field=models.FileField(blank=True, upload_to=sqwbase.models.rename_pdb),
        ),
    ]
