# Generated by Django 2.0 on 2018-01-17 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sqwbase', '0012_calculation_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoleculeTaskMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('molecule', models.ManyToManyField(to='sqwbase.Molecule')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqwbase.Project')),
                ('task', models.ManyToManyField(to='sqwbase.Task')),
            ],
        ),
    ]
